server.port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: bookings

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://${DATABASE_SERVER:localhost:5432/demo}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8070/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
