server.port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://${DATABASE_SERVER:localhost:5432/demo}

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8070/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

